Remove Url import from endpoint template
no longer needed after #33, and causing an error when building with these types:
error TS6133: 'Url' is declared but its value is never read.